var items = [{
    url: "tv1.html",
    productName: "Philips 50\" 4K UHD Smart TV50PUS6162",
    ref: "Artikelnummer: 50PUS6162",
    review: "3.5 (2)",
    energyIcon: "",
    price: "4 990",
    description: "Philips 50\" 4K UHD Smart TV 50PUS6162 är en smart-TV med 4K UHD 2160p-upplösning, fyrkärnig processor, 700 PPI och Wi-Fi.",
    description1: "50\" LED Smart TV",
    description2: "4K UHD, HDR+",
    description3: "Quad Core, 6162 series",
    specifications: "https://www.philips.se/c-p/50PUS6162_12/6000-series-smart-ultratunn-led-tv-med-4k-och-pixel-plus-ultra-hd",
    productImage: "style/img/tv1.jpg",
    stars: " stars3H_big"
},
{
    url: "tv2.html",
    productName: "Samsung 40\" 4K UHD Smart TVUE40MU6175",
    ref: "Artikelnummer: UE40MU6175XXC",
    review: "4.5 (5)",
    energyIcon: "",
    price: "5 790",
    description: "Samsung 40\" 4K UHD Smart TV UE40MU6175 fungerar inte bara som TV när du vill titta på program eller filmer, du kan också välja mellan en otrolig mängd online media så som t.ex. Youtube och många andra tack vare Smart Hub",
    description1: "40\" LED Smart TV",
    description2: "4K UHD, HDR",
    description3: "Tizen, 6 series",
    specifications: "http://www.samsung.com/se/support/model/UE40MU6175UXXC",
    productImage: "style/img/tv2.jpg",
    stars: " stars4H_big"
},
{
    url: "tv3.html",
    productName: "Samsung 55\" 4K UHD Smart TVUE55MU7005",
    ref: "Artikelnummer: UE55MU7005XXC",
    review: "4.0 (4)",
    energyIcon: "",
    price: "11 790",
    description: "Samsung 55\" 4K UHD Smart TV UE55MU7005 imponerar med kristallklar bildkvalitet, 4K UHD 2160p upplösning.",
    description1: "55\" LED Smart TV",
    description2: "4K UHD, HDR, PQI 2300",
    description3: "Slim 360 design, 7 series",
    specifications: "http://www.samsung.com/se/tvs/uhdtv-mu7005/UE55MU7005TXXC/",
    productImage: "style/img/tv3.jpg",
    stars: " stars4_big"
},
{
    url: "tv4.html",
    productName: "Samsung 55\" 4K UHD Smart TVUE55MU8005",
    ref: "Artikelnummer: UE55MU8005XXC",
    review: "5.0 (1)",
    energyIcon: "",
    price: "12 990",
    description: "Utforska en värld av smarta funktioner med Samsung 55\" 4K UHD Smart TV UE55MU8005. Låt dig fångas av den kristallklara bildkvaliteten med imponerande svärta och vithetsgrad. 4K UHD 2160p upplösning garanterar en fantastisk upplevelse framför din TV",
    description1: "55\" LED Smart TV",
    description2: "4K UHD, HDR, PQI 2600",
    description3: "Slim 360 design, 8 series",
    specifications: "http://www.samsung.com/se/support/model/UE55MU8005TXXC",
    productImage: "style/img/tv4.jpg",
    stars: " stars5_big"
},
{
    url: "tv5.html",
    productName: "Sony 75\" 4K UHD Smart TVKD-75XE8596",
    ref: "Artikelnummer: KD75XE8596BAE",
    review: "4.5 (2)",
    energyIcon: "",
    price: "22 222",
    description: "Sony 75'' 4K UHD Smart TV KD-75XE8596 har en läcker tunn design + och en kraftfull 4K Processor X1 Extreme för snabb hantering av flera funktioner och teknologier samtidigt.",
    description1: "75\" LED Smart-TV",
    description2: "4K HDR PROCESSOR X1",
    description3: "Android TV, XE85 series",
    specifications: "https://www.sony.se/electronics/tv-apparater/XE8505-XE8566-XE8577-XE8588-XE8596-XE8599-Series",
    productImage: "style/img/tv5.jpg",
    stars: " stars4H_big"
},
{
    url: "tv6.html",
    productName: "Sony 65\" 4K UHD Smart TVKD-65XE9305BAE",
    ref: "Artikelnummer: KD65XE9305BAE",
    review: "4.0 (6)",
    energyIcon: "",
    price: "22 990",
    description: "Sony 65\" 4K UHD Smart TV KD-65XE9305BAE har en läcker tunn design, unika teknologin Slim Backlight Drive + och en kraftfull 4K Processor X1 Extreme för snabb hantering av flera funktioner och teknologier samtidigt.",
    description1: "65\" LED Smart-TV",
    description2: "4K HDR Processor X1 Extreme",
    description3: "Android TV, XE93 series",
    specifications: "https://www.sony.se/electronics/tv-apparater/xe9305-xe9405-series",
    productImage: "style/img/tv6.jpg",
    stars: " stars4_big"
},
{
    url: "headphones1.html",
    productName: "Philips brusreducerande och trådlösa On-ear hörlurar",
    ref: "Artikelnummer: SHB8850",
    review: "4.0 (72)",
    energyIcon: "",
    price: "1 290",
    description: "Topptestade och kundfavoriten tack vare kraftfullt ljud med aktiv brusreducering, Bluetooth och NFC. Övertygande och bra diskant, bas och bra batteritid. En av årets bästa trådlösa hörlurar med brusreducering av What HiFi och M3 rekommenderar.",
    description1: "Aktiv brusreducerande teknik",
    description2: "Bluetooth 4.0 med NFC",
    description3: "Headset funktion",
    specifications: "https://www.philips.se/c-p/SHB8850NC_00/tradloesa-hoerlurar-med-brusreducering",
    productImage: "style/img/headphones1.jpg",
    stars: " stars4_big"
},
{
    url: "headphones2.html",
    productName: "Bose SoundLink 2 Hörlurar around-ear (svart)",
    ref: "Artikelnummer: SLAE2BK",
    review: "4.0 (8)",
    energyIcon: "",
    price: "2 222",
    description: "Med Bose SoundLink trådlösa around-ear hörlurar II kan du lyssna på musik i total frihet. Med den inbyggda mikrofonen kan du dessutom hålla kontakten med omgivningen.",
    description1: "Trådlösa hörlurar",
    description2: "Bluetooth",
    description3: "Inbyggd mikrofon",
    specifications: "https://www.bose.se/sv_se/products/headphones/over_ear_headphones/soundlink-around-ear-wireless-headphones-ii.html",
    productImage: "style/img/headphones2.jpg",
    stars: " stars4_big"
},
{
    url: "headphones3.html",
    productName: "Beats Studio3 trådlösa around-ear hörlurar (grå)",
    ref: "Artikelnummer: BEATSMQUF2ZMA",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "3 490",
    description: "Beats Studio3 trådlösa around-ear hörlurar ger dig kristallklar musik - också i högljudda omgivningar, utan irriterande sladdar och enkla anslutningsmöjligheter.",
    description1: "Trådlösa around-ear hörlurar",
    description2: "Apple W1-chip",
    description3: "Pure aktiv brusreducering",
    specifications: "https://www.beatsbydre.com/se/headphones/studio3-wireless",
    productImage: "style/img/headphones3.jpg",
    stars: " starsN_big"
},
{
    url: "speakers1.html",
    productName: "Marshall Acton BT högtalare (svart)",
    ref: "Artikelnummer: ACTONBTBL",
    review: "4.5 (21)",
    energyIcon: "",
    price: "1 111",
    description: "Marshall Acton BT är en kompakt aktiv stereohögtalare som ger dig ett stort ljud i en mycket snygg klassisk Marshall design.",
    description1: "Trådlös högtalare",
    description2: "Bluetooth",
    description3: "Dubbelsidig 3,5 mm kabel",
    specifications: "https://www.marshallheadphones.com/mh_se_en/acton-bluetooth",
    productImage: "style/img/speakers1.jpg",
    stars: " stars4H_big"
},
{
    url: "speakers2.html",
    productName: "Audio Pro Addon T14 Aktiv högtalare - 2 st (svart)",
    ref: "Artikelnummer: ADDONT14BK",
    review: "4.5 (49)",
    energyIcon: "",
    price: "3 990",
    description: "Två eleganta, aktiva högtalare med kraftfullt ljud (100 Watt). Audio Pro Addon T14 förbättrar ljudet från din TV, dator eller smartphone.",
    description1: "2 x 50 Watt högtalare",
    description2: "Bluetooth 4.0 Apt-X",
    description3: "Fyra olika ingångar",
    specifications: "https://www.audiopro.com/product/addon-t14/#black",
    productImage: "style/img/speakers2.jpg",
    stars: " stars4H_big"
},
{
    url: "speakers3.html",
    productName: "Bose SoundTouch 30 Series III trådlöst Musiksystem svar",
    ref: "Artikelnummer: BOSEST30BKV3",
    review: "5.0 (3)",
    energyIcon: "",
    price: "5 790",
    description: "Njut av musik med hög ljudkvalitet med SoundTouch 30 Series III trådlösa musiksystem. Perfekt när du vill fylla stora rum med kraftfullt ljud.",
    description1: "Trådlöst musiksystem",
    description2: "Bluetooth och Wi-Fi",
    description3: "Stöttar Spotify och Deezer",
    specifications: "https://www.bose.se/sv_se/products/speakers/multi_room_speakers/soundtouch-30-wireless-music-system.html",
    productImage: "style/img/speakers3.jpg",
    stars: " stars5_big"
},
{
    url: "mobile1.html",
    productName: "HTC U Ultra smartphone 64 GB (svart)",
    ref: "Artikelnummer: HTCULTRABK",
    review: "3.5 (4)",
    energyIcon: "",
    price: "5 990",
    description: "En smartphone som handlar helt om dig. HTC U Ultra har en elegant design som kombinerar metall med rundat glas i olika lager. Den superskarpa 5,7” QHD-skärmen kompletteras av en andra skärm på toppen för viktiga aviseringar, genvägar och appar.",
    description1: "5,7\" QHD + 2\" Dual Display",
    description2: "Android 7.0 Nougat",
    description3: "12 MP + 16 MP kameror",
    specifications: "http://www.htc.com/se/smartphones/htc-u-ultra/",
    productImage: "style/img/mobile1.jpg",
    stars: " stars3H_big"
},
{
    url: "mobile2.html",
    productName: "Samsung Galaxy S8 smartphone (svart)",
    ref: "Artikelnummer: SAMS864BK",
    review: "4.5 (23)",
    energyIcon: "",
    price: "7 490",
    description: "Samsung S8 tar klassisk Samsung tillförlitlighet till nästa nivå med ännu mera smart och innovativ teknik.",
    description1: "5,8” Infinity-skärm",
    description2: "Android 7.0 Nougat",
    description3: "Dubbla kameror 12/8 Mp",
    specifications: "http://www.samsung.com/se/smartphones/galaxy-s8/?gclid=Cj0KCQjw1dDPBRC_ARIsAJZrQfp1Nhw2rql4rJTECuB2jKdwX7us5Sjims6iVSH5zfxL76bcJNyXOigaAsAQEALw_wcB&s_kwcid=AL!618!3!224850062803!b!!g!!%2Bsamsung%20%2Bgalaxy%20%2Bs8&cid=se_ppc-Google+Adwords-8613118529-cam_%28SE%29+IM+%7C+Phones+%7C+Galaxy+S8+%26+S8%2B-kw_%2Bsamsung%20%2Bgalaxy%20%2Bs8-mt_b-Aud_kwd-70935490554&ef_id=WfGqwAAAAZZoGQzo:20171028223637:s",
    productImage: "style/img/mobile2.jpg",
    stars: " stars4H_big"
},
{
    url: "mobile3.html",
    productName: "Sony Xperia XZ Premium smartphone (brons, rosa)",
    ref: "Artikelnummer: SONXPXZPBP",
    review: "4.5 (8)",
    energyIcon: "",
    price: "7 490",
    description: "Sony Xperia XZ Premium smartphone kommer med en ultrastylad design och en ram tillverkad i aluminium, Gorilla Glass på både fram och baksidan som ger dig en vattensäker och dammsäker konstruktion.",
    description1: "5.5\" 4k HDR-skärm",
    description2: "Android 7.1 Nougat",
    description3: "IP65/68-klassad",
    specifications: "https://www.sonymobile.com/se/products/phones/xperia-xz-premium/?gclid=CjwKCAjw-NXPBRB4EiwAVNRLKuxANsVN5LpLZZbjGcJYUQokggvwqeuA5s5CvGNsIADmiFzzppdkQhoC9MkQAvD_BwE",
    productImage: "style/img/mobile3.jpg",
    stars: " stars4H_big"
},
{
    url: "mobile4.html",
    productName: "Motorola Moto Z2 Force smartphone (svart)",
    ref: "Artikelnummer: MOTOZ2FBK",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "7 990",
    description: "Motorola Moto Z2 Force smartphone kommer chocka med sin stilrena metalldesign och tålighet mot fall. Den har en kraftfull Qualcomm Snapdragon 835-processor och dubbla 12 Mpx kameror på baksidan. Moto Z2 Force sätter ny standard för mobiltelefoner.",
    description1: "5,5\" Super AMOLED-skärm",
    description2: "Android 7.1 Nougat",
    description3: "12 Mpx dubbla kameror på baksidan",
    specifications: "https://www.moto.com/se/products/moto-z-family?gclid=CjwKCAjw-NXPBRB4EiwAVNRLKrsNUKYDy_zK8V2cs-9fa_t-88puyE_9PILxfoESSz5I996v2OpWqxoCNbUQAvD_BwE",
    productImage: "style/img/mobile4.jpg",
    stars: " starsN_big"
},
{
    url: "mobile5.html",
    productName: "Samsung Galaxy Note8 smartphone (guld)",
    ref: "Artikelnummer: SAMN864GO",
    review: "5.0 (3)",
    energyIcon: "",
    price: "9 990",
    description: "Samsung Galaxy Note8 med Infinity Display utan ram garanterar en uppslukande upplevelse. Telefonen kommer med en S Pen som låter dig teckna, skissa eller ta anteckningar med skärmen avstängd samt en dubbel kamera som fångar skarpa och snygga bilder.",
    description1: "6,3\" Infinity Display",
    description2: "12 megapixels dubbla kameror",
    description3: "Vattentålig, S Pen",
    specifications: "http://www.samsung.com/se/smartphones/galaxy-note8/",
    productImage: "style/img/mobile5.jpg",
    stars: " stars5_big"
},
{
    url: "mobile6.html",
    productName: "iPhone X smartphone 256GB (silver)",
    ref: "Artikelnummer: APPIPX256SI",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "13 190",
    description: "Upplev otroliga iPhone X med kant-till-kant 5,8” Super Retina-skärm och en mängd otroliga funktioner så som Face ID-ansiktsupplåsning, personliga animojis och mer.",
    description1: "5.8\" Super Retina skärm",
    description2: "Face ID och Animojis",
    description3: "Dual 12 Mpx kamera, 4K video",
    specifications: "https://www.apple.com/shop/buy-iphone/iphone-x/5.8-inch-display-256gb-silver-tmobile",
    productImage: "style/img/mobile6.jpg",
    stars: " starsN_big"
},
{
    url: "phone1.html",
    productName: "Panasonic KX-TGB210 Trådlös telefon",
    ref: "Artikelnummer: KXTGB210",
    review: "4.0 (33)",
    energyIcon: "", price: "4 990",
    description: "Lätthanterlig trådlös telefon med upp till 16 timmar batteritid (taltid), stora och tydliga knappar samt alarm.",
    description1: "Alarm",
    description2: "Lång batteritid",
    description3: "1 telefon medföljer",
    specifications: "http://www.panasonic.com/se/consumer/telefoner/tradlosa-telefoner/kx-tgb210ne.html",
    productImage: "style/img/phone1.jpg",
    stars: " stars4_big"
},
{
    url: "phone2.html",
    productName: "Panasonic KX-TGD310 Trådlös Telefon",
    ref: "Artikelnummer: KXTGD310",
    review: "4.5 (3)",
    energyIcon: "",
    price: "399",
    description: "Praktisk trådlös telefon från Panasonic med stor 1,8\" TFT-skärm och förlängd användningstid.",
    description1: "Trådlös telefon",
    description2: "Förlängd batteritid till 16 tim",
    description3: "Tydlig och klar 1,8\" skärm",
    specifications: "http://www.panasonic.com/se/consumer/telefoner/tradlosa-telefoner/kx-tgd310neg.html",
    productImage: "style/img/phone2.jpg",
    stars: " stars4H_big"
},
{
    url: "phone3.html",
    productName: "Gigaset C430 Duo Trådlös Telefon",
    ref: "Artikelnummer: GIGAC430DUO",
    review: "4.5 (51)",
    energyIcon: "",
    price: "699",
    description: "Gigaset C430 är en praktisk trådlös telefon med 1,8\" färgskärm och bra ljudkvalitet, även när du använder handsfree, med denna duo lösning får du två telefoner.",
    description1: "1,8\" färgskärm",
    description2: "2 telefonenheter",
    description3: "Spara upp till 150 kontakter",
    specifications: "http://www.gigaset.com/se_se/gigaset-c430-silver/",
    productImage: "style/img/phone3.jpg",
    stars: " stars4H_big"
},
{
    url: "gps1.html",
    productName: "TomTom Via 52 GPS Europa Lifetime",
    ref: "Artikelnummer: TTVIA52LMT",
    review: "4.5 (6)",
    energyIcon: "",
    price: "1 449",
    description: "TomTom Via 52 GPS erbjuder full navigering över Europa med livstids kartuppdatering. Med Bluetooth anslutning kan du göra hands-free samtal med din smartphone.",
    description1: "5\" pekskärm",
    description2: "Livstids kartor över Europa",
    description3: "Bluetooth, TomTom Traffic",
    specifications: "https://www.tomtom.com/sv_se/drive/car/products/via-52/",
    productImage: "style/img/gps1.jpg",
    stars: " stars4H_big"
},
{
    url: "gps2.html",
    productName: "Garmin DriveLuxe 50LMT-D Europa",
    ref: "Artikelnummer: GADRL50LMTDE",
    review: "5.0 (4)",
    energyIcon: "",
    price: "2 490",
    description: "Premium GPS sat nav med dubbelriktad multi-touch skärm, gratis kartor och trafikuppdateringar. GPS-en kommer att göra allt förutom att köra bilen för dig, med syfte att öka din uppmärksamhet i trafiken.",
    description1: "5,1\" multi-touch skärm",
    description2: "Kartor över Europa",
    description3: "Kontinuerliga kartor och trafikuppdateringar",
    specifications: "https://buy.garmin.com/sv-SE/SE/p/523251",
    productImage: "style/img/gps2.jpg",
    stars: " stars5_big"
},
{
    url: "gps3.html",
    productName: "TomTom GO 6200 WLMT 6\" bil GPS",
    ref: "Artikelnummer: TTGO6200WLMT",
    review: "4.0 (7)",
    energyIcon: "",
    price: "3 790",
    description: "Smartare och snabbare än någonsin, TomTom GO 6200 erbjuder dig en 6 tums pekskärm, förladdade kartor över Europa, nedladdningbara världskartor med livstids uppdateringar, uppdateringar om fartkameror och inbyggt SIM för uppdaterad trafikinformation.",
    description1: "6 tums pekskärm, inbyggt SIM",
    description2: "Uppdateringar via Wi-Fi",
    description3: "Livstids kart och kamerauppdateringar",
    specifications: "https://www.tomtom.com/sv_se/drive/car/products/go-6200/",
    productImage: "style/img/gps3.jpg",
    stars: " stars4_big"
},
{
    url: "computer1.html",
    productName: "HP 14-bp093no 14\" bärbar dator (svart)",
    ref: "Artikelnummer: HP14BP093NO",
    review: "4.0 (2)",
    energyIcon: "",
    price: "4 495",
    description: "Eleganta HP 14-bp093no bärbar dator levererar stabil prestanda med kompetent 7:e generationens Intel Pentium processor, 14\" Full HD-skärm, snabb SSD-lagring och upp till 11 timmars batterikapacitet.",
    description1: "Laddas snabbt",
    description2: "Pålitlig prestanda",
    description3: "Stilren design",
    specifications: "http://www8.hp.com/se/sv/products/laptops/product-detail.html?oid=17193311",
    productImage: "style/img/computer1.jpg",
    stars: " stars4_big"
},
{
    url: "computer2.html",
    productName: "Lenovo Yoga 520 2-i-1 14\" (svart)",
    ref: "Artikelnummer: LE80X800H3MX",
    review: "5.0 (1)",
    energyIcon: "",
    price: "6 995",
    description: "Lenovo Yoga 520 2-i-1 kombinerar effektiva funktioner och teknologier för arbete och lek i farten. 7:e generationens Intel Pentium processor, 14\" Full HD IPS pekskärm och Harman högtalare förser dig med en unik multimediaupplevelse.",
    description1: "Intel Pentium 4415U processor",
    description2: "14\" Full HD anti glare touch-skärm",
    description3: "4 GB RAM DDR4, 128 GB PCIe SSD",
    specifications: "https://www3.lenovo.com/se/sv/laptops/yoga/500-series/Yoga-520-14/p/88YG5000829",
    productImage: "style/img/computer2.jpg",
    stars: " stars5_big"
},
{
    url: "computer3.html",
    productName: "Acer Swift 5 14\" bärbar dator Signature Edition ",
    ref: "Artikelnummer: ACNXGLDED005",
    review: "4.5 (15)",
    energyIcon: "",
    price: "9 990",
    description: "Acer Swift 5 14-tums bärbara dator är elegant, väldigt lätt att ta med sig och blandar solid prestanda med sjunde generationens Core i5 processor och utmärkt responsivitet med SSD-lagring. Acer Swift 5 har upp till 13 h av batteritid.",
    description1: "Intel Core i5-7200U processor",
    description2: "Full HD IPS-skärm",
    description3: "8GB RAM, 256GB PCIe SSD",
    specifications: "https://www.acer.com/ac/en/US/content/models/laptops/swift5",
    productImage: "style/img/computer3.jpg",
    stars: " stars4H_big"
},
{
    url: "computer4.html",
    productName: "MacBook Air 13.3\" MQD32",
    ref: "Artikelnummer: MACAMQD32KSA",
    review: "4.5 (6)",
    energyIcon: "",
    price: "9 990",
    description: "MacBook Air med 13,3\" skärm och femte generation Intel Core i5-processor som levererar kraft som varar hela dagen.",
    description1: "Intel Core i5, 1.8 GHz",
    description2: "Intel HD Graphics 6000",
    description3: "8 GB RAM, 128 GB SSD",
    specifications: "https://www.apple.com/se/macbook-air/specs/",
    productImage: "style/img/computer4.jpg",
    stars: " stars4H_big"
},
{
    url: "computer5.html",
    productName: "MSI GS63VR 7RF-218NE Stealth Pro 15.6\" bärbar dator",
    ref: "Artikelnummer: MSIGS637RF218",
    review: "4.5 (2)",
    energyIcon: "",
    price: "17 990",
    description: "MSI GS63VR 7RF-218NE Stealth Pro 15.6\" bärbara gamingdator är ett kompakt kraftpaket som är enkelt att ta med sig överallt.",
    description1: "Nvidia GTX 1060, 6 GB",
    description2: "Intel Core i7-7700HQ CPU",
    description3: "1 TB HDD + 256 GB SSD",
    specifications: "https://www.msi.com/Laptop/GS63VR-7RF-Stealth-Pro.html",
    productImage: "style/img/computer5.jpg",
    stars: " stars4H_big"
},
{
    url: "computer6.html",
    productName: "MacBook Pro 15.4\" Retina-skärm MJLQ2",
    ref: "Artikelnummer: MACBPMJLQ2KSA",
    review: "5.0 (9)",
    energyIcon: "",
    price: "18 790",
    description: "MacBook Pro är utrustad med en otrolig Retina-skärm, snabb Intel Core i7-processor och flashminne, samtidigt som den har en tunn och lätt design.",
    description1: "2.2 GHz Intel Core i7 processor",
    description2: "Intel Iris Pro-grafik",
    description3: "16 GB RAM, 256 GB flashminne",
    specifications: "https://www.apple.com/se/macbook-pro/specs-2015/",
    productImage: "style/img/computer6.jpg",
    stars: " stars5_big"
},
{
    url: "compStation1.html",
    productName: "HP Envy 27-b110no 34\" stationär dator (grå)",
    ref: "Artikelnummer: HP34B010NO",
    review: "5.0 (1)",
    energyIcon: "",
    price: "24 990",
    description: "Ett modernt utseende möter solid prestanda. Så beskrivs HP Envy 34-b110no all-in-one, en stationär dator med en rad spännande egenskaper. Datorn har en välvd 34\" WQHD IPS skärm, Nvidia-grafik, B&O Play högtalare och Intel Core i7 processor.",
    description1: "Intel Core i7-7700T CPU",
    description2: "Curved 34\" WQHD screen",
    description3: "Nvidia GTX 950M, B&O sound",
    specifications: "http://store.hp.com/SwedenStore/Merch/Product.aspx?id=Z7C67EA&opt=UUW&sel=DTP",
    productImage: "style/img/compStation1.jpg",
    stars: " stars5_big"
},
{
    url: "compStation2.html",
    productName: "DreamHack Streamer x99 stationär dator gaming",
    ref: "Artikelnummer: DHPCSTEAMXV1",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "38 390",
    description: "Dreamhack PC Streamer levererar prestanda för den avancerade användaren med högsta upplösningen. Fantastisk maskin för youtubers och streamare.",
    description1: "Core i7 6850K 3.6 GHz 15MB s2011-3",
    description2: " ASUS ROG STRIX X99 GAMING",
    description3: "512GB Samsung 960 Pro, M.2 (2280) NVMe",
    specifications: "http://dreamhackpc.com/dreamhack-pc-streamer/",
    productImage: "style/img/compStation2.jpg",
    stars: " starsN_big"
},
{
    url: "compStation3.html",
    productName: "Microsoft Surface Studio stationär dator 32 GB",
    ref: "Artikelnummer: MSSSI732",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "49 195",
    description: "Microsoft Surface Studio stationära all-in-one-dator ger dig närmast obegränsade möjligheter för både arbetsrelaterade- och kreativa uppgifter. Datorn har bland annat en 28 tums PixelSense Display med otroliga 13,5 miljoner pixlar.",
    description1: "28\" PixelSense display",
    description2: "32 GB RAM, 2.1 TB hybrid HDD",
    description3: "Desktop och Studio Mode",
    specifications: "https://www.microsoft.com/sv-se/surface/devices/surface-studio/overview",
    productImage: "style/img/compStation3.jpg",
    stars: " starsN_big"
},
{
    url: "keyboard1.html",
    productName: "Turtle Beach Impact 700 Tangentbord Gaming",
    ref: "Artikelnummer: TBEARIMP700",
    review: "5.0 (2)",
    energyIcon: "",
    price: "1 222",
    description: "Turtle Beach Impact 700 är ett hållbart tangentbord för gaming. Det har en stålförstärkt design med exakta Cherry MX-tangentbrytare och justerbar bakbelysning.",
    description1: "Cherry MX-brytare",
    description2: "Justerbar bakbelysning",
    description3: "2 USB-portare",
    specifications: "https://shop.turtlebeach.com/us/impact-700",
    productImage: "style/img/keyboard1.jpg",
    stars: " stars5_big"
},
{
    url: "keyboard2.html",
    productName: "Corsair Strafe RGB Tangentbord gaming (svart)",
    ref: "Artikelnummer: CORSTRAFCHRED",
    review: "4.5 (3)",
    energyIcon: "",
    price: "1 590",
    description: "Corsair Strafe RGB är ett fullt programmerbart mekaniskt gaming-tangentbord med extra tystgående Cherry MX red-brytare som erbjuder maximal precision och coola ljuseffekter",
    description1: "Cherry MX red-brytare",
    description2: "RGB-belysning",
    description3: "MOBA- och FPS-tangenter",
    specifications: "http://www.corsair.com/en-eu/strafe-rgb-mechanical-gaming-keyboard-cherry-mx-silent",
    productImage: "style/img/keyboard2.jpg",
    stars: " stars4H_big"
},
{
    url: "keyboard3.html",
    productName: "Razer Blackwidow X Chroma tangentbord gaming",
    ref: "Artikelnummer: RAZBWCHROMAX",
    review: "5.0 (2)",
    energyIcon: "",
    price: "1 790",
    description: "Razer Blackwidow X Chroma tangentbord gaming levererar turneringsklassad prestanda med förstklassig precision tack vare Razers mekaniska huvudbrytare, anpassningsbar Chroma-belysning och fullt programmerbara tangenter.",
    description1: "Razer mekaniska brytare",
    description2: "Justerbar Chroma belysning",
    description3: "On-the-fly makroinspelning",
    specifications: "https://www.razerzone.com/gaming-keyboards-keypads/razer-blackwidow-x-chroma",
    productImage: "style/img/keyboard3.jpg",
    stars: " stars5_big"
},
{
    url: "mouse1.html",
    productName: "Asus ROG Gladius 2 gamingmus",
    ref: "Artikelnummer: ASUMOUSEGLAII",
    review: "4.5 (3)",
    energyIcon: "",
    price: "949",
    description: "Asus ROG Gladius 2 gamingmus bjuder på ett revolutionerande steg mot sin föregångare, men behåller alla smarta funktioner. Snabb och precis optisk sensor med 12000 DPI och 250 IPS låter dig styra spelen med dödlig precision.",
    description1: "Optisk sensor med 12000 DPI",
    description2: "DPI target-knapp",
    description3: "Micro-USB anslutning",
    specifications: "https://www.asus.com/us/ROG-Republic-Of-Gamers/ROG-Gladius-II/",
    productImage: "style/img/mouse1.jpg",
    stars: " stars4H_big"
},
{
    url: "mouse2.html",
    productName: "Razer Mamba Chroma Gamingmus",
    ref: "Artikelnummer: RAZMAMBACHOMA",
    review: "3.0 (9)",
    energyIcon: "",
    price: "1 395",
    description: "Med Razer Mamba Chroma datormus till gaming har den typiska designen och ultimat precision. Du kan välja mellan med eller utan sladd och mellan miljontals färgkombinationer på belysningen.",
    description1: "16000 dpi lasersensor",
    description2: "Chroma-belysning",
    description3: "Användning med eller utan sladd",
    specifications: "https://www.razerzone.com/gaming-mice/razer-mamba",
    productImage: "style/img/mouse2.jpg",
    stars: " stars3_big"
},
{
    url: "mouse3.html",
    productName: "Logitech G903 Lightspeed trådlös gamingmus",
    ref: "Artikelnummer: LTG903",
    review: "5.0 (1)",
    energyIcon: "",
    price: "1 895",
    description: "Kräver du precision och pålitlighet är trådlösa Logitech G903 Lightspeed en perfekt mus för dig, oberoende om du är vänster- eller högerhänt.",
    description1: "Tvåhänt, 11 knappar",
    description2: "Lightspeed trådlös anslutning",
    description3: "Kompatibel med Powerplay",
    specifications: "https://www.logitechg.com/sv-se/product/g903-wireless-gaming-mouse",
    productImage: "style/img/mouse3.jpg",
    stars: " stars5_big"
},
{
    url: "compactCam1.html",
    productName: "Panasonic Lumix GX800 kompaktkamera (svart)",
    ref: "Artikelnummer: DMCGX800BLK",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "4 790",
    description: "Utforska nya platser och dela de med världen. Panasonic Lumix GX800 är en kompaktkamera som tillåter dig att fånga fantastiska upplevelser genom bilder eller 4K-video. Vändbar skärm är perfekt för när du ska ta selfies.",
    description1: "4K-video",
    description2: "180 graders vändbar skärm",
    description3: "Post Focus-funktion",
    specifications: "http://www.panasonic.com/se/consumer/foto-och-videokamera/lumix-g-compact-system-cameras-dslm/dc-gx800k.html",
    productImage: "style/img/compactCam1.jpg",
    stars: " starsN_big"
},
{
    url: "compactCam2.html",
    productName: "Canon PowerShot G1X Mark 2 kompaktkamera",
    ref: "Artikelnummer: POWSG1XMK2",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "5 990",
    description: "Canon PowerShot G1X Mark 2 kompaktkamera kommer med en stor sensor av 1,5-typ. PowerShot G1 X Mark II har en yta som mäter 18,7 x 14,0 mm – nästan lika stor som en APS-C-sensor.",
    description1: "13.1 Mpix CMOS sensor",
    description2: "Perfekt för foton i dåligt ljus",
    description3: "Tiltbar pekskärm",
    specifications: "https://www.canon.se/for_home/product_finder/cameras/digital_camera/powershot/powershot_g1x_mark_ii/",
    productImage: "style/img/compactCam2.jpg",
    stars: " starsN_big"
},
{
    url: "compactCam3.html",
    productName: "Sony CyberShot RX100 Mark 5 kompaktkamera",
    ref: "Artikelnummer: DSCRX100M5",
    review: "5.0 (8)",
    energyIcon: "",
    price: "9 990",
    description: "Sony CyberShot RX100 Mark 5 är en kompaktkamera med prestanda hos en DSLR. Missa aldrig ett kort med ultrasnabb autofokus och kontinuerlig fotografering. Ett mycket bra objektiv kommer ge dig högkvalitativa foton även under dåliga ljusförhållanden.",
    description1: "20 MP sensor, 4K video",
    description2: "Hybrid AF/315 fokuspunkter",
    description3: "1000 fps HFR fotografering",
    specifications: "https://www.sony.se/electronics/cyber-shot-kompaktkameror/dsc-rx100",
    productImage: "style/img/compactCam3.jpg",
    stars: " stars5_big"
},
{
    url: "actionCam1.html",
    productName: "Garmin VIRB X Actionkamera + fästen",
    ref: "Artikelnummer: VIRBX",
    review: "4.5 (7)",
    energyIcon: "",
    price: "2 490",
    description: "Rejäl, hållbar och helt vattentät actionkamera för filmning i Full HD och extremsporter som rafting och dykning. Lägg till extra effekter med hjälp av G-Metrix sensorer.",
    description1: "12,4 megapixel CMOS-sensor",
    description2: "1080/30p Full HD video",
    description3: "Vattentät ner till 50 meter",
    specifications: "https://buy.garmin.com/sv-SE/SE/p/164723",
    productImage: "style/img/actionCam1.jpg",
    stars: " stars4H_big"
},
{
    url: "actionCam2.html",
    productName: "GoPro HERO 5 Black actionkamera",
    ref: "Artikelnummer: VIRBX",
    review: "4.5 (20)",
    energyIcon: "",
    price: "3 790",
    description: "Spela in dina äventyr, resor och mest minnesvärda ögonblick med tuffa och stryktåliga GoPro HERO5 Black actionkamera. Filma stabilt i otrolig 4K UHD upplösning, skapa time-lapse eller slowmotion-videor var du än är.",
    description1: "12 Mpix sensor",
    description2: "4K UHD/30 fps video",
    description3: "Vattentät ner till 10 m",
    specifications: "https://shop.gopro.com/EMEA/cameras/hero5-black/CHDHX-502-master.html",
    productImage: "style/img/actionCam2.jpg",
    stars: " stars4H_big"
},
{
    url: "actionCam3.html",
    productName: "Sony FDR-X3000R actionkamera + Finger Grip",
    ref: "Artikelnummer: FDRX3000RFDR",
    review: "4.0 (1)",
    energyIcon: "",
    price: "5 789",
    description: "Kompakta Sony FDR-X3000R är en actionkamera för att fånga dina reseminnen, aktiviteter och ditt sportutövande i 4K med möjlighet för höghastighetsinspelning för dramatiska slow motion-videor. Kameran tål tuffa förhållanden och utmanande väder.",
    description1: "4K 2160p video",
    description2: "240 fps inspelningshastighet",
    description3: "WiFi, Bluetooth, NFC",
    specifications: "https://www.sony.se/electronics/actioncam/fdr-x3000-body-kit",
    productImage: "style/img/actionCam3.jpg",
    stars: " stars4_big"
},
{
    url: "systemCam1.html",
    productName: "Nikon D5600 Systemkamera +18-55 mm AF-P DX-objektiv",
    ref: "Artikelnummer: D56001855VR",
    review: "5.0 (1)",
    energyIcon: "",
    price: "6 995",
    description: "Tänj på gränserna för ditt kreativa uttryck med den kraftfulla systemkameran Nikon D5600. Kameran levereras med snabbt och tyst 18-55 mm AF-P-objektiv, avancerat AF system, flip-out pekskärm och ständig trådlös SnapBridge anslutning.",
    description1: "24.2 MP CMOS-sensor",
    description2: "Nikon SnapBridge",
    description3: "Inklusive 18-55 mm AF-P DX-objektiv",
    specifications: "https://store.nikon.se/d5600-+-af-p-dx-18-55-vr/VBA500K001/details",
    productImage: "style/img/systemCam1.jpg",
    stars: " stars5_big"
},
{
    url: "systemCam2.html",
    productName: "Canon EOS 80D DSLR + 18-55mm IS STM objektiv",
    ref: "Artikelnummer: EOS80D1855ISS",
    review: "5.0 (3)",
    energyIcon: "",
    price: "12 265",
    description: "Utveckla dina fotokunskaper till en högre nivå med den högpresterande Canon EOS 80D DSLR. Kameran kommer med högupplöst CMOS APS- C sensor, RGB och IR sensor samt Dual Pixel autofokus.",
    description1: "24.2 Mpix APS-C CMOS",
    description2: "Canon 18-55mm IS STM objektiv",
    description3: "Full HD 1080/60p video",
    specifications: "https://www.canon.se/press-centre/press-releases/2016/02/unlock-creative-potential/",
    productImage: "style/img/systemCam2.jpg",
    stars: " stars5_big"
},
{
    url: "systemCam3.html",
    productName: "Canon EOS 80D DSLR + 18-55mm IS STM objektiv",
    ref: "Artikelnummer: EOS80D1855ISS",
    review: "4.5 (6)",
    energyIcon: "",
    price: "17 790",
    description: "Sony Alpha 7 Mark 2 systemkamera har 24.3 MP fullformatsensor, 5-axlad bildstabilisator, Wi-Fi- och NFC-funktioner och videoinspelning i Full HD 1080p.",
    description1: "24.3 MP fullformatssensor",
    description2: "Full Hd-videoinspelning 1080p",
    description3: "Medföljande 28 - 70mm objektiv",
    specifications: "https://www.sony.co.uk/electronics/interchangeable-lens-cameras/ilce-7m2-body-kit",
    productImage: "style/img/systemCam3.jpg",
    stars: " stars4H_big"
},
{
    url: "videoCam1.html",
    productName: "Canon Legria HF R87 videokamera (svart)",
    ref: "Artikelnummer: HFR87BLK",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "3 790",
    description: "Fånga de viktigaste ögonblicken i ditt liv med Canon Legria HF R87. Videokameran filmar i Full HD och ser till att du inte missar några detaljer. Dela dina videofilmer trådlöst via WiFi och NFC.",
    description1: "Full HD videokamera",
    description2: "57x avancerad zoom",
    description3: "WiFi med NFC delning",
    specifications: "https://www.canon.se/for_home/product_finder/camcorders/high_definition_hd/legria_hf_r87/",
    productImage: "style/img/videoCam1.jpg",
    stars: " starsN_big"
},
{
    url: "videoCam2.html",
    productName: "Panasonic HC-W580 Twin Videokamera (svart)",
    ref: "Artikelnummer: HCW580BLK",
    review: "4.5 (3)",
    energyIcon: "",
    price: "3 995",
    description: "HC-W580 är en videokamera med dubbla kameror för bild-i-bild-filmning, vidvinkelobjektiv, 50x optisk zoom, 90x intelligent zoom, inbyggt Wi-Fi och NFC.",
    description1: "2 x Full HD-sensorer",
    description2: "50x optisk zoom",
    description3: "WiFi med NFC",
    specifications: "http://www.panasonic.com/se/consumer/foto-och-videokamera/videokamera/hc-w580eg-k.html",
    productImage: "style/img/videoCam2.jpg",
    stars: " stars4H_big"
},
{
    url: "videoCam3.html",
    productName: "Sony FDR-AX100 4K Videokamera (svart)",
    ref: "Artikelnummer: FDRAX100BLK",
    review: "5.0 (8)",
    energyIcon: "",
    price: "16 990",
    description: "Förstklassig videokamera från Sony som filmar i 4K, har en ultrakänslig Exmor R-sensor på 20 MP och kraftfullt Zeiss-objektiv för otrolig filmkvalitet.",
    description1: "4K videokamera, 20 MP sensor",
    description2: "3,5\" LCD-pekskärm",
    description3: "12x optisk zoom",
    specifications: "https://www.sony.se/electronics/handycam-videokameror/fdr-ax100e",
    productImage: "style/img/videoCam3.jpg",
    stars: " stars5_big"
},
{
    url: "headset1.html",
    productName: "Logitech G933 Artemis Spectrum Gaming headset",
    ref: "Artikelnummer: LTG933",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "1 190",
    description: "Spelhörlurar för audiofiler med överlägset omslutande ljud, Dolby 7.1 och DTS Headphone:X för PC, konsoler, mobiler och hemmabiosystem. Inställningsbar RGB-belysning gör att du kan välja mellan 16,8 miljoner färger.",
    description1: "7.1 surroundljud",
    description2: "Justerbar belysning",
    description3: "USB-adapter för trådlös anslutning",
    specifications: "https://www.logitechg.com/en-ca/product/g933-7-1-surround-sound-gaming-headset",
    productImage: "style/img/headset1.jpg",
    stars: " starsN_big"
},
{
    url: "headset2.html",
    productName: "Sennheiser G4ME ZERO Gaming headset (vit)",
    ref: "Artikelnummer: SENG4MEZERO",
    review: "5.0 (5)",
    energyIcon: "",
    price: "1 990",
    description: "Sennheiser G4ME ZERO är ett headset som är otroligt bekvämt så att du kan spela hur länge du vill. Den stängda designen gör att du får en väldigt detaljerad ljudupplevelse.",
    description1: "Högpresterande gaming headset",
    description2: "Avancerad brusreducering",
    description3: "Kompatibel med din dator",
    specifications: "https://sv-se.sennheiser.com/game-zero",
    productImage: "style/img/headset2.jpg",
    stars: " stars5_big"
},
{
    url: "headset3.html",
    productName: "SteelSeries Siberia 840 trådlöst headset för gaming",
    ref: "Artikelnummer: SSSIBERIA840",
    review: "Lämna omdömme",
    energyIcon: "",
    price: "3 290",
    description: "Med SteelSeries Siberia 840 trådlöst headset för gaming, kan du spela obegränsat med verklighetstroget 7.1 DTS virtuellt surround ljud. Dubbel trådlös anslutning gör att du kan använda headsetet till din PC, spelkonsol eller mobila enhet.",
    description1: "7.1 DTS H:X surroundljud",
    description2: "RF + Bluetooth trådlös",
    description3: "2 hot-swap-batterier",
    specifications: "https://steelseries.com/gaming-headsets/siberia-840",
    productImage: "style/img/headset3.jpg",
    stars: " starsN_big"
},
{
    url: "console1.html",
    productName: "Nintendo Switch gaming konsol + Joy-Con (grå)",
    ref: "Artikelnummer: SWI32GBGREY",
    review: "4.5 (23)",
    energyIcon: "",
    price: "3 390",
    description: "Med Nintendo Switch kan du spela hur och var du vill. Joy-Con kontrollerna kan spelas handhållna, eller så ansluter du konsolen direkt i TV:n. Du kan också spela med bägge kontrollerna i varsin hand eller ihop med en kompis.",
    description1: "Rörelsekänsliga Joy-Con kontroller",
    description2: "Handhållet eller dockat läge",
    description3: "6.2\" HD skärm, 6 timmar batteritid",
    specifications: "https://www.nintendo.com/switch/buy-now/",
    productImage: "style/img/console1.jpg",
    stars: " stars4H_big"
},
{
    url: "console2.html",
    productName: "PlayStation 4 Slim (PS4) 500 GB med 2x DualShock (guld)",
    ref: "Artikelnummer: PS4500GBDCGO",
    review: "5.0 (1)",
    energyIcon: "",
    price: "4 390",
    description: "Den innovativa Playstation 4 Slim underhållningssystem kommer i ett mindre och lättare chassi med lägre strömförbrukning. Njut av HDR teknologi med kompatibla spel för den perfekta spelupplevelsen. 2x DualShock kontroller inkluderas.",
    description1: "Tunnare och lättare design",
    description2: "Stöd för HDR",
    description3: "2x DualShock kontroller",
    specifications: "https://www.playstation.com/sv-se/explore/ps4/?emcid=pa-pe-109183&utm_medium=Paid_Search&utm_campaign=&utm_source=&utm_term=pa-pe-109183&utm_content=",
    productImage: "style/img/console2.jpg",
    stars: " stars5_big"
},
{
    url: "console3.html",
    productName: "Xbox One X 1 TB (svart)",
    ref: "Artikelnummer: XONEX1TB",
    review: "5.0 (1)",
    energyIcon: "",
    price: "5 390",
    description: "Gör dig redo till nästa nivå med högkvalitativ gaming och digital underhållning. Xbox One X spelkonsol ger dig exceptionell prestanda tack vare en grafikenhet med 6 teraflops kraft samt 12 GB grafikminne.",
    description1: "Kraftull konsol till 4K gaming",
    description2: "4K Blu-ray, HDR, WCG",
    description3: "1 TB hårddisk",
    specifications: "https://www.microsoft.com/sv-se/store/d/xbox-one-x-1-tb-konsol/8nq33jvv1s9v",
    productImage: "style/img/console3.jpg",
    stars: " stars5_big"
},
{
    url: "control1.html",
    productName: "Logitech Joystick Extreme 3D Pro (PC/Mac)",
    ref: "Artikelnummer: LTEXT3DPRO",
    review: "4.0 (7)",
    energyIcon: "",
    price: "499",
    description: "Med denna avancerade joystick kan du anpassa kontrollerna efter din unika spelstil.",
    description1: "12 actionknappar",
    description2: "Avancerad joystick",
    description3: "Knapp för snabbskjutning",
    specifications: "https://www.logitechg.com/en-us/product/extreme-3d-pro-joystick",
    productImage: "style/img/control1.jpg",
    stars: " stars4_big"
},
{
    url: "control2.html",
    productName: "Nya PS4 DualShock 4 trådlösa handkontroll (matt svart)",
    ref: "Artikelnummer: PS4DUALS4BLV2",
    review: "4.5 (4)",
    energyIcon: "",
    price: "590",
    description: "Med den nydesignade PS4 Dualshock 4 handkontrollen får du ännu bättre kontroll när du spelar på din Playstation 4. Kontrollen har uppgraderade analoga knappar för utökad precision och en LED-belyst remsa som byter färg efter aktivitet.",
    description1: "Trådlös PS4 handkontroll",
    description2: "Touchpad med ljusremsa",
    description3: "Förbättrad kontroll",
    specifications: "https://www.playstation.com/sv-se/explore/accessories/dualshock-4-wireless-controller/",
    productImage: "style/img/control2.jpg",
    stars: " stars4H_big"
},
{
    url: "control3.html",
    productName: "Logitech G29 Driving Force Ratt till racingspel",
    ref: "Artikelnummer: LTG29",
    review: "4.5 (58)",
    energyIcon: "",
    price: "2 990",
    description: "Ta dina bilspel till nya nivåer. Denna racingratt har dubbla force feedback-motorer, fotpedaler i rostfritt stål och en pedalmodul som ger ultimat realism.",
    description1: "Dubbla Force Feedback-motorer",
    description2: "Gas, broms, koppling",
    description3: "Till PC, PS4, PS3",
    specifications: "https://www.logitechg.com/sv-se/product/g29-driving-force",
    productImage: "style/img/control3.jpg",
    stars: " stars4H_big"
}]


/*
function loadSearchResults() {

    var previousBajstolle = localStorage.getItem('searchResults');
    var bajstolle;

    if (previousBajstolle === null) {
        bajstolle = {
            searchItems: [],
        }

        localStorage.setItem('seachResults', JSON.stringify(bajstolle));
    }
    else {
        order = JSON.parse(previousBajstolle);
    }
    return bajstolle;
}*/